/*
 * hscript-seiun — SeiunEngine's merged HaxeScript runtime (MIT).
 *
 * Derivative work merged from these MIT-licensed projects:
 *   hscript (Haxe Foundation), hscript-iris (crowplexus, Ne_Eo),
 *   hscript-improved (FNF-CNE-Devs), hscript-plus (Dlean Jeans).
 * See LICENSE and NOTICE for details.
 */
package crowplexus.hscript;

/**
 * Implemented by shadow classes generated by the `ClassExtendMacro` (`_HSX`)
 * so that field reads/writes from scripts are routed through the instance's
 * `Interp` (hscript-improved behavior, FNF-CNE-Devs, MIT).
 */
interface IHScriptCustomBehaviour {
	public function hset(name:String, val:Dynamic):Dynamic;
	public function hget(name:String):Dynamic;
}
