name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        haxe-version: [latest, 4.3.7]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@v2
      with:
        haxe-version: ${{ matrix.haxe-version }}
    - name: Register local library
      run: haxelib dev hscript-seiun .
    - name: Run interpreter test-suite
      run: |
        haxe -cp . -cp test -D hscriptPos -D CUSTOM_CLASSES \
          --macro 'hscript.macros.UsingHandler.init()' \
          --macro 'hscript.macros.ClassExtendMacro.init()' \
          -main TestMain --interp
